![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## 5-MODUL. Machine Learning

### Portfolio uchun vazifa: Toshkent shahrida uylarning narxini aniqlash.

Ushbu amaliyotda sizning vazifangiz berilgan ma`lumotlar asosida Toshkent shahridagi uylarning narxini aniqlash.

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')
df.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57,4,4,52000
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52,4,5,56000
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42,4,4,37000
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65,1,4,49500
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70,3,5,55000

# Ustunlar ta'rifi
- `location` - sotilayotgan uy manzili
- `district` - uy joylashgan tuman
- `rooms` - xonalar soni
- `size` - uy maydoni (kv.m)
- `level` - uy joylashgan qavat
- `max_levels` - ja'mi qavatlar soni
- `price` - uy narxi

## Vazifani CRSIP-DM Metolodgiyasi yordamida bajaring.
<img src="https://i.imgur.com/dzZnnYi.png" alt="CRISP-DM" width="800"/>

In [5]:
df.value_counts()

location                                                 district           rooms  size   level  max_levels  price
город Ташкент, Яккасарайский район, Кушбеги              Яккасарайский      2      48     5      9           23000    20
                                                                                   64     1      5           42000    13
город Ташкент, Мирзо-Улугбекский район, Ялангач          Мирзо-Улугбекский  2      50     1      4           30000    11
город Ташкент, Учтепинский район, Чиланзар 15-й квартал  Учтепинский        2      42     4      5           28500    10
город Ташкент, Яккасарайский район, Кушбеги              Яккасарайский      3      80     4      5           56000    10
                                                                                                                      ..
город Ташкент, Учтепинский район, 5-й проезд Гулистон    Учтепинский        2      57.95  11     12          29000     1
город Ташкент, Учтепинский район, 4-й проезд Такачи      Учтепинский        3      85     7      9           52500     1
город Ташкент, Учтепинский район, 4-й проезд Курувчи     Учтепинский        2      56     1      4           40500     1
город Ташкент, Учтепинский район, 30 kvartal 29 dom      Учтепинский        3      80     3      12          47500     1
город Ташкент, Учтепинский район, Атой                   Учтепинский        2      56     1      4           40500     1
Name: count, Length: 6865, dtype: int64